# Generated by Django 4.2.16 on 2024-11-01 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodejour",
            name="nbre_qr",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="nombre de qr code par generation",
            ),
        ),
    ]
