# Generated by Django 4.2.16 on 2024-11-01 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_qrcodejour_nbre_qr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodegenerator",
            name="qr_code_jour",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.qrcodejour",
            ),
        ),
    ]
