# Generated by Django 4.2.16 on 2024-11-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_qrcodegenerator_qr_code_jour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodegenerator",
            name="code",
            field=models.TextField(
                unique=True, verbose_name="code de verification du qr code"
            ),
        ),
    ]
