# Generated by Django 4.2.16 on 2024-11-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_alter_qrcodegenerator_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodegenerator",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/", verbose_name="QR code"
            ),
        ),
    ]
