# Generated by Django 4.1 on 2024-11-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_qrcodegenerator_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodegenerator",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="QR code"
            ),
        ),
    ]
