# Generated by Django 4.2.16 on 2024-11-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_qrcodegenerator_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qrcodegenerator",
            name="code_chiffre",
            field=models.TextField(
                unique=True, verbose_name="code de verification du qr code chiffrer"
            ),
        ),
    ]
