# Generated by Django 4.2.16 on 2024-11-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_userinfo_registre"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registre",
            name="motif",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="motif "
            ),
        ),
    ]
